### ISSUE TITLE
No camera feed and warning UNHANDLED ERROR

### ISSUE THREAD

**Issue by futandrew** [node-alarm-dot-com/homebridge-node-alarm-dot-com#105]
I just set up this in my Homebridge. Other devices (like switches) work fine and can be detected. Not the camera feed. Here is the error message in the logs. 

```
UNHANDLED ERROR: Error: Received no partitions from Alarm.com
    at /volume1/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:184:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by chase9** [comment]
We don't support cameras, so that's why you're not seeing them. Pull requests welcome but I think due to the conversion work for the camera stream, it would need to be an additional plugin.

Curious about the error you're seeing. Do you have partitions on your system? ASAIK there is no way to have an alarm.com account without one...

**Comment by chase9** [comment]
Closing the camera issue as not supported. Please open a new issue if there are still problems with the partition error you list.
