### ISSUE TITLE
no longer login to Alarm.com

### ISSUE THREAD

**Issue by mrimkus** [node-alarm-dot-com/homebridge-node-alarm-dot-com#128]
**Describe the bug**

Hoobs is no longer signing in to alarm.com. I have not change my password. This just started today. Everything was working fine until about noon today. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**ADC-SystemStates.json**

**Homebridge System (please complete the following information):**
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker Raspbin
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Additional context**

**Comment by chase9** [comment]
Please fill out the information above about your homebridge system and include any relevant logs. I can't help troubleshoot without more information.

**Comment by mercnmash** [comment]
Hello!

I have also started experiencing this problem since yesterday.

- Expected behavior: Login successful and control of alarm.com system possible through homebridge/homekit
- Error seen homebridge logs: _"loginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo ENOTFOUND www.alarm.com"_
- No response from security system and not changeable
- Node.js Version	v18.16.0
- Homebridge v 1.7
- Operating System: Running homebridge on pi using Docker

**Comment by pintapass** [comment]
I'm seeing this too. I've successfully configured this in the past and have entered everything correctly in the plugin config.

Logs:

```
Error: Error: GET https://www.alarm.com/web/api/systems/systems/11864646 failed: Two factor is enabled on this account but not setup in the plugin. See the wiki for details
    at get (/var/lib/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:627:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at authenticatedGet (/var/lib/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:584:17)
    at getCurrentState (/var/lib/homebridge/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:166:17)
    at async Promise.all (index 0)
    at ADCPlatform.listDevices (/var/lib/homebridge/node_modules/homebridge-node-alarm-dot-com/src/index.ts:353:26)
[28/01/2024, 10:57:48] [Govee] [LAN] client enabled and found 0 device(s).
```

Node.js Version: v20.11.0
NPM Version: 10.2.4
Homebridge Version: 1.7.0
Operating System: Debian GNU/Linux Bookworm (12)
Process Supervisor: Bare metal on a Pi 4b.

**Comment by chase9** [comment]
I'm going to close this since I haven't heard back from the OP, so please file a new issue if you have one. Before filing a new issue, please make sure you have enabled two-factor on your account and set that up. Alarm.com has been silently forcing two-factor for years now, so that really is the most reliable way to go.
