### ISSUE TITLE
Homebridge 2.0 Compatibility

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#137]
Please ensure this works with Homebridge 2.0

**Comment by scottleestrange** [comment]
Hey,

Soon Homebridge 2.0 will be released which will have some breaking changes to plugins.
Could you please check if this plugin is impacted and make it work with 2.0?

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by loganzugg5165** [comment]
Have the same issue. Updated to 2.0 and now can't use my alarm.com integration. Any fix here?

**Comment by chase9** [comment]
I went through and it looks like we aren't affected by any of the breaking changes in HAP-NodeJS 1.0, and I don't see any specific breaking changes published for Homebridge 2.0. Are you telling me there is an issue, or asking me to check for you?

**Comment by loganzugg5165** [comment]
> @scottleestrange I went through and it looks like we aren't affected by any of the breaking changes in HAP-NodeJS 1.0, and I don't see any specific breaking changes published for Homebridge 2.0. Are you telling me there is an issue, or asking me to check for you?
> 
> @loganzugg5165 awesome, any issues pop up in the two weeks since you've published this?

No issues working great.

**Comment by loganzugg5165** [comment]
> > @scottleestrange I went through and it looks like we aren't affected by any of the breaking changes in HAP-NodeJS 1.0, and I don't see any specific breaking changes published for Homebridge 2.0. Are you telling me there is an issue, or asking me to check for you?
> > @loganzugg5165 awesome, any issues pop up in the two weeks since you've published this?
> 
> No issues working great.

@chase9 I have no been able to set my alarm status to "Away" I can set it home, night, and off but not away to activate the motion detectors. This is the following error I'm receiving from Homebridge. Any insight??  

![image](https://github.com/user-attachments/assets/01918c8e-67ea-45f4-9cae-e25fa9a2ce06)

**Comment by chase9** [comment]
Check your arming options for away. Looks like you're sending an option that your panel doesn't support.ChaseOn Dec 7, 2024, at 6:16 PM, loganzugg5165 ***@***.***> wrote:﻿


@scottleestrange I went through and it looks like we aren't affected by any of the breaking changes in HAP-NodeJS 1.0, and I don't see any specific breaking changes published for Homebridge 2.0. Are you telling me there is an issue, or asking me to check for you?
@loganzugg5165 awesome, any issues pop up in the two weeks since you've published this?

No issues working great.

@chase9 I have no been able to set my alarm status to "Away" I can set it home, night, and off but not away to activate the motion detectors. This is the following error I'm receiving from Homebridge. Any insight??
image.png (view on web)

**Comment by chase9** [comment]
Marking this as closed in v1.10.2. Thanks for testing everyone!
