### ISSUE TITLE
Can't remove "night" arming mode?

### ISSUE THREAD

**Issue by jfmach** [node-alarm-dot-com/homebridge-node-alarm-dot-com#67]
Hello,

Not a bug, more of a question as I can't figure out how to do this. The "night" arming mode does not work for me, I always get "no response" and all I really need is "home" and "away" anyway so I want to remove it.

I tried removing "night" from the list of "armingModes" in the plugin configuration, then restarted homebridge, but the "Night" arming mode is still listed in the Home app.

Am I doing something wrong?

Thanks a ton,

- Jeff

**Comment by ngori** [comment]
Hi,  I'm not running the latest version yet (a new baby is taking priority) but I suspect you would need to remove night arming from not only the config but also the index.ts here in homebridge-node-alarm-dot-com but possibly also in node-alarm-dot-com where that state is imported from.

**Comment by DacoDev** [comment]
I may be wrong but I believe it might be required or necessary to have the Night mode because of how Homekit handles security systems. I remember reading something similar when I was looking to integrate Abode with Homekit; even from Abode one of the arming modes was ported to "night" mode because the Homekit "buttons"/controls don't read the states from the source, they just have their own pre-determined interface.

**Comment by chase9** [comment]
From what I understand, @DacoDev is right. The three arming modes are built into homekit and cannot be removed. The best you can do is check to make sure your config matches for stay and night and then, at least, it'll be arming with the same parameters.

**Comment by jfmach** [comment]
Understood, thank you!
