### ISSUE TITLE
Leak sensor reversed

### ISSUE THREAD

**Issue by LokiThorne** [node-alarm-dot-com/homebridge-node-alarm-dot-com#98]
I have a newly installed security system, and I’m having a problem with one sensor. By only leak sensor is showing that it’s triggered in Homebridge , but it’s not showing an alarm on the security panel. Is there a solution to this?

**Comment by chase9** [comment]
There were improvements in 1.9.0 to sensor tracking. Are you still seeing this issue after updating to 1.9.0?

**Comment by LokiThorne** [comment]
Well, now all of my sensors are triggered.  I think the problem just got worse.

**Comment by datasage** [comment]
Seeing the same issue here.

**Comment by chase9** [comment]
@datasage are you seeing any errors in your log? Could you try clearing your accessories cache and reporting back?

**Comment by datasage** [comment]
@chase9 Might be more of an alarm.com issue than anything else. 

I have an DSC alarm system connected to alarm.com. The sensors appeared to be showing the correct status within the local system. Alarm.com had the incorrect status cached. Installer needed to reset the state in alarm.com and everything has been fine since.

**Comment by chase9** [comment]
Great to hear! If no one else speaks up soon, I'll close this as solved.
